name: Build and Test

on:
  push:
    branches:
      - main
    paths:
      - 'include/**'
      - '.github/workflows/**'
      - 'tests/**'
      - 'examples/**'
      - 'benchmarks/**'

  pull_request:
    branches:
      - main
    paths:
      - 'include/**'
      - '.github/workflows/**'
      - 'tests/**'
      - 'examples/**'
      - 'benchmarks/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build in Dev Container
        uses: devcontainers/ci@v0.3
        with:
          push: never
          runCmd: |
            cmake --preset release-test-gcc
            cmake --build --preset build-release-test
            cd build && ctest --output-on-failure --output-junit test-results.xml
      
      - name: Test Report
        if: ${{ !cancelled() }}
        uses: dorny/test-reporter@v3
        with:
          name: C++ Tests
          path: build/test-results.xml
          reporter: java-junit
          fail-on-error: true
          list-tests: failed
          list-suites: failed
          max-annotations: 50